### PR TITLE
Sr init doc

### PR DESCRIPTION
**Pull request by SebastienRietteMTO**
This branch contains modifications around the initialisation.
It conflicts with the current status of the master branch.
Two kinds of conflicts exist:
- those due to the change in the reference version of Meso-NH
- those due to other modifications in the PHYEX repository. For those ones, the https://github.com/SebastienRietteMTO/PHYEX/tree/SR_init2 branch contain a merged version of these files checked with arome (including the lima test case) and testprogs.

### CODE REVIEW

**Comment by QuentinRodier** [comment]
Hi Sebastien, some files of mesonh/ext were not taken from 5.5.1 MesoNH version (such as default_desfmn, deallocate_model1). Do you know the list of all the files not taken from it ?

**Comment by SebastienRietteMTO** [comment]
Except if I did some mistakes (largely possible) all new tracked files introduced in the branch have been taken from the reference version of MesoNH at the time I made the branch: sxphynh:/home/rodierq/REF/MNH-V5-5-1-1abfa259/

**Comment by QuentinRodier** [comment]
In shallow_mf_pack; for now, I left the hard-coded option LSTATNW=FALSE 
LOGICAL :: LSTATNW  !  switch for HARMONIE-AROME turb physics option
                    ! TODO: linked with modd_turbn + init at default_desfmn

**Comment by QuentinRodier** [comment]
The branch [SR_init_work](https://github.com/UMR-CNRM/PHYEX/tree/SR_init_work) is a working branch to merge this PR. A first shot merge is done and now must be tested on all models (I will do)

**Comment by QuentinRodier** [comment]
The test case with LRED=F is not bit-repro on a lot's of variables (007_16janvier/008_run2_lredf) : is it wanted/expected ? @SebastienRietteMTO

**Comment by SebastienRietteMTO** [comment]
The SR_init_doc branch is based on 5.5.1 and the last commit of the branch reproduce the 5.5.1 reference run:
check_commit_mesonh.sh -s  -t 007_16janvier/008_run2_lredf 7679597c81eb25c082157f437feae96a8b4229eb refQuentin
...
### Check commit 7679597c81eb25c082157f437feae96a8b4229eb against commit refQuentin
Compare with python...
status1 = 0
status2 = 0
Compare with ncdump...
...comparison done: OK

**Pull request merged**
